csm:
	./load_csm_mongo.py ../../data/csm/NFCC_Benthic_Biomonitoring_2011-2018_MASTER__alldata.txt -H ../../data/csm/nfcc_taxalist_02112020-sheet1.txt

install:
	python3 -m pip install -r requirements.txt
