csm:
	./load_csm_mongo.py ../../data/csm/NFCC_Benthic_Biomonitoring_2011-2018_MASTER__alldata.txt -H ../../data/csm/NFCC_TaxaList_02112020__sheet1.txt

install:
	python3 -m pip install -r requirements.txt
